"""add source_type and source_name columns

Revision ID: 4b9e6e784edd
Revises: 2db5b32466a9
Create Date: 2023-09-07 11:32:52.934739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b9e6e784edd'
down_revision = '2db5b32466a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_cards', sa.Column('source_type', sa.String(), nullable=True))
    op.add_column('photo_cards', sa.Column('source_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo_cards', 'source_name')
    op.drop_column('photo_cards', 'source_type')
    # ### end Alembic commands ###
