"""add follows table

Revision ID: 5e44d6443a3d
Revises: 4b9e6e784edd
Create Date: 2023-09-12 11:19:09.238115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e44d6443a3d'
down_revision = '4b9e6e784edd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower', sa.Integer(), nullable=False),
    sa.Column('followee', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followee'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower', 'followee', name='fol_uix_1')
    )
    op.create_index(op.f('ix_follows_id'), 'follows', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_follows_id'), table_name='follows')
    op.drop_table('follows')
    # ### end Alembic commands ###
