"""add upload column to users table

Revision ID: fde4182ba1ec
Revises: cf777943c771
Create Date: 2023-08-07 17:33:03.322404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde4182ba1ec'
down_revision = 'cf777943c771'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('upload', sa.Boolean()))
    op.execute("UPDATE users SET upload = 'false'")
    op.alter_column('users', 'upload', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'upload')
    # ### end Alembic commands ###
