# This workflow has 2 jobs that:
# 1. Do a clean installation of node dependencies, cache/restore them, build the source code and run tests with a single version of Node
# 2. Will install Python dependencies, run tests and lint with a single version of Python

name: KFan Development Workflow

on:
  push:
  pull_request:
    branches: [ "main" ]

permissions:
    contents: read    

jobs:
  test-frontend:

    defaults: 
      run: 
        working-directory: ./frontend-ts
        
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend-ts/package-lock.json
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  test-backend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      working-directory: ./backend/app
    - name: Test with pytest
      run: |
        pytest
      working-directory: ./backend/app
    
